#Spring boot application.yml
server:
  port: 8080
  undertow:
    accesslog:
      enabled: true
      dir: ../logs
  error:
    whitelabel:
      enabled: false
springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method
    #custom path for api docs
    url: /doc/openapi.json
spring:
  kafka:
    producer:
      ssl:
        key-password: