name: Run Plugin

on:
  repository_dispatch:
    types: [run-plugin]

jobs:
  use-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Set Artifact URL
        run: |
          ARTIFACT_ID="${{ github.event.client_payload.artifact_id }}"
          ARTIFACT_URL="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_ID}/zip"
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_ENV

      - name: Download Artifact
        run: |
          echo "Downloading artifact from ${{ env.artifact_url }}"
          curl -L -o smart-doc-source.zip -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ env.artifact_url }}"
          echo "File details:"
          file smart-doc-source.zip
          echo "File size:"
          ls -lh smart-doc-source.zip

      - name: Unzip Artifact
        run: |
          unzip smart-doc-source.zip -d ~/.m2/repository/com/github/linwumingshi || (echo "Unzip failed, printing file content:" && cat smart-doc-source.zip && exit 1)
