name: Run Plugin

on:
  repository_dispatch:
    types: [run-plugin]

jobs:
  use-artifact:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set Artifact URL
      - name: Set Artifact URL
        run: |
          ARTIFACT_ID="${{ github.event.client_payload.artifact_id }}"
          if [ -z "$ARTIFACT_ID" ]; then
            echo "Error: ARTIFACT_ID is not set."
            exit 1
          fi
          ARTIFACT_URL="https://api.github.com/repos/linwumingshi/common/actions/artifacts/${ARTIFACT_ID}/zip"
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_ENV

      # Step 2: Download Artifact
      - name: Download Artifact
        run: |
          echo "Downloading artifact from ${{ env.artifact_url }}"
          curl -L -o smart-doc-source.zip -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ env.artifact_url }}"
          echo "Download status: $?"
          echo "File details:"
          file smart-doc-source.zip
          echo "File size:"
          ls -lh smart-doc-source.zip

      # Step 3: Create Directory and Move File
      - name: Create Directory and Move File
        run: |
          mkdir -p ~/.m2/repository/com/github/linwumingshi
          mv smart-doc-source.zip ~/.m2/repository/com/github/linwumingshi/
          echo "Listing files in target directory:"
          ls -lh ~/.m2/repository/com/github/linwumingshi

      # Step 4: Unzip Artifact
      - name: Unzip Artifact
        run: |
          echo "Unzipping artifact..."
          unzip -d ~/.m2/repository/com/github/linwumingshi ~/.m2/repository/com/github/linwumingshi/smart-doc-source.zip || (echo "Unzip failed, printing file content:" && cat ~/.m2/repository/com/github/linwumingshi/smart-doc-source.zip && exit 1)
          ls -lh ~/.m2/repository/com/github/linwumingshi
