name: Generate API Docs When Smart Doc PR With Local And Notify Smart Doc Status

on:
  repository_dispatch:
    types: [run-plugin]

jobs:
  generate-docs-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Example Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Verify Repository
        run: |
          if [ "${{ github.event.repository.full_name }}" != "linwumingshi/common" ]; then
            echo "This event is not from a trusted source."
            exit 0
          fi

      - name: Set Maven Local Repository Path for Plugin Dependencies
        run: echo "MAVEN_OPTS='-Dmaven.repo.local=$GITHUB_WORKSPACE/.m2/repository-plugin'" >> $GITHUB_ENV

      - name: Download Plugin Artifact
        uses: actions/download-artifact@v4
        with:
          name: plugin-artifact
          path: .m2/repository-plugin

      - name: Run Maven to Generate API Docs with Plugin Dependencies
        id: generate-docs
        run: |
          mvn -DskipTests=true clean package

      - name: Determine Status
        id: determine-status
        run: |
          if [ "${{ steps.generate-docs.outcome }}" == "success" ]; then
            echo "status=success" >> $GITHUB_ENV
          else
            echo "status=failure" >> $GITHUB_ENV

      - name: Trigger Completion Workflow in Repo Smart Doc
        if: always()
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"event_type\": \"docs-generation-complete\", \"client_payload\": {\"status\": \"$STATUS\", \"run_id\": \"${{ github.event.client_payload.run_id }}\", \"repo\": \"${{ github.event.client_payload.repo }}\"}}" \
          https://api.github.com/repos/${{ github.event.client_payload.repo }}/dispatches
        env:
          STATUS: ${{ env.status }}
