name: Generate API Docs When Smart Doc PR With Local And Notify Smart Doc Status

on:
  repository_dispatch:
    types: [run-plugin]

jobs:
  generate-docs-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Example Repository
        uses: actions/checkout@v4

      - name: Verify Repository
        run: |
          if [ "${{ github.event.repository.full_name }}" != "linwumingshi/common" ]; then
            echo "This event is not from a trusted source."
            exit 0
          fi

      - name: Download a Build Artifact
        uses: indiesdev/curl@v1.1
        with:
          curl-url: "${{ github.event.client_payload.artifact_url }}"

      - name: unzip Artifact
        run: |
          unzip smart-doc-source.zip -d ~/.m2/repository/com/github/linwumingshi

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'


      - name: Install Project Dependencies
        run: mvn install

      - name: Run Maven to Generate API Docs with Plugin Dependencies
        id: generate-docs
        run: |
          mvn -DskipTests=true clean package
